### PR TITLE
Various CI tweaks

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Based on post-merge review of https://github.com/sociomantic-tsunami/turtle/pull/1

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @leandro-lucarella-sociomantic

**Comment by mathias-baumann-sociomantic** [comment]
I'd review it, but I'd have no idea if any of this is correct ^^

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, damn, this has the regular merge configured by default, I think I did a regular merge :grumpy:

**Comment by mihails-strasuns-sociomantic** [comment]
I won't tell anyone, your secret is safe.

**Pull request merged**
