### PR TITLE
Replace usage of to-be-deprecated ocean.core.Time

### PR DESCRIPTION
**Pull request by Geod24**
See sociomantic-tsunami/ocean#812

### CODE REVIEW

**Comment by don-clugston-sociomantic** [comment]
LGTM

**Comment by don-clugston-sociomantic** [comment]
Unfortunately I don't have write access to this repo to merge it :(

**Comment by Geod24** [comment]
CC @daniel-zullo-sociomantic @ben-palmer-sociomantic

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Pull request merged**
