### PR TITLE
Upgrade all sumbodules for new major

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This looks like a WIP... :thinking:

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic 

> This looks like a WIP

I have encountered weird circleci problem and trying to debug it :( See https://github.com/sociomantic-tsunami/turtle/pull/24/commits/e547fcb84038364a96597f438006f8e574b32c5f

**Comment by mihails-strasuns-sociomantic** [comment]
Found workaround, not WIP anymore.

**Comment by leandro-lucarella-sociomantic** [comment]
Yuck! So you have to commit that once to make it work? Because I don't see it in the current commits...

**Comment by mihails-strasuns-sociomantic** [comment]
> Yuck! So you have to commit that once to make it work? Because I don't see it in the current commits...

I have found that providing `ssh` and `git` inside docker image (and thus not having circleci to fallback to host binaries) fixes the problem as well - https://github.com/sociomantic-tsunami/turtle/pull/28

It could as well be that cache just got flushed while I was messing with this problem but it works for now. We will know for sure by the time of next turtle major ;)

**Pull request merged**
