### PR TITLE
CircleCI script, no-caching sudo version

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
`mihailsstrasunssociomantic/dlang` is generated like this:

```Dockerfile
FROM sociomantictsunami/dlang:xenial-v3
RUN useradd -g users -m testrunner
RUN echo "testrunner ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/testrunner
```

**Comment by mihails-strasuns-sociomantic** [comment]
Version that copies current travis functionality (just matrix tests, no codecov or d2tag) is finished and ready for review. Full matrix took 2:18 with parallelization available for free accounts, average time spent in each step installing dependencies is 10 to 15 seconds.

Workflow overview: https://circleci.com/workflow-run/0e5fd5d6-6d28-4734-b5c9-63f9eafba37e

One idea that came to my mind is that we can speed up installation by pregenerating `sociomantictsunami/turtle` image with all dependencies but DMD being already installed and only pick required compiler package from already present apt cache. That should only take few seconds.

**Comment by mihails-strasuns-sociomantic** [comment]
For comparison, reported run time for last travis build for turtle is 4:30

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic do you want anything else done for the initial version?

**Comment by leandro-lucarella-sociomantic** [comment]
I think is good to go for an initial step.

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks! I will add coverage and d2tag support as separate ones. Could you please enable codecov for turtle btw?

**Comment by leandro-lucarella-sociomantic** [comment]
Done.

**Pull request merged**
